import type { TravelBriefResponse } from '@/lib/anthropic'

interface TravelBriefTextProps {
  data: TravelBriefResponse
}

export default function TravelBriefText({ data }: TravelBriefTextProps) {
  const brief = data.structuredData

  const formatList = (items: string[], prefix = '• '): string => {
    return items.map(item => `${prefix}${item}`).join('\n')
  }

  const formattedText = `# Travel Brief for ${brief.destination}

${brief.startDate && brief.endDate ? `**Travel Dates:** ${new Date(brief.startDate).toLocaleDateString()} - ${new Date(brief.endDate).toLocaleDateString()}` : ''}

## 🚇 Transportation & Getting Around

### Public Transit
${formatList(brief.transportation.publicTransit)}

### Alternative Transportation
${formatList(brief.transportation.alternatives)}

### Payment Methods
${formatList(brief.transportation.paymentMethods)}

### Transportation Tips
${formatList(brief.transportation.tips)}

## 📸 Must-See Attractions & Photo Spots

### Top Attractions
${formatList(brief.attractions.mustSee)}

### Photo Spots
${formatList(brief.attractions.photoSpots)}

### Museums & Cultural Sites
${formatList(brief.attractions.museums)}

### Unique Experiences
${formatList(brief.attractions.experiences)}

## 🍽️ Food & Drink

### Local Specialties
${formatList(brief.foodAndDrink.localSpecialties)}

### Recommended Restaurants
${formatList(brief.foodAndDrink.restaurants)}

### Cafes & Coffee Culture
${formatList(brief.foodAndDrink.cafes)}

### Bars & Nightlife
${formatList(brief.foodAndDrink.bars)}

### Street Food
${formatList(brief.foodAndDrink.streetFood)}

## 🏘️ Neighborhoods & City Layout

### Key Areas
${brief.neighborhoods.areas.map(area => 
  `• **${area.name}**: ${area.character}\n  ${formatList(area.highlights, '  - ')}`
).join('\n\n')}

### City Layout
${formatList(brief.neighborhoods.layout)}

### Where to Stay
${formatList(brief.neighborhoods.whereToStay)}

## 🎭 Culture & Events

### Events During Your Visit
${formatList(brief.cultureAndEvents.events)}

### Cultural Customs
${formatList(brief.cultureAndEvents.customs)}

### Etiquette Tips
${formatList(brief.cultureAndEvents.etiquette)}

### Language Tips
${formatList(brief.cultureAndEvents.language)}

## 💡 Practical Information

**Currency:** ${brief.practical.currency}
**Exchange Rate:** ${brief.practical.exchangeRate}

### Tipping Customs
${formatList(brief.practical.tipping)}

### Emergency Information
${formatList(brief.practical.emergency)}

### Safety Tips
${formatList(brief.practical.safety)}

### Local News & Current Events
${formatList(brief.practical.localNews)}

---
*Generated by TripBrief • Double-check current information before traveling*`

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
      <div className="prose dark:prose-invert max-w-none">
        <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed">
          {formattedText}
        </div>
      </div>
    </div>
  )
}