import type { TravelBriefResponse } from '@/lib/anthropic'
import { countryCodeToFlag, toTitleCase } from '@/lib/utils'

interface TravelBriefTextProps {
  data: TravelBriefResponse
}

export default function TravelBriefText({ data }: TravelBriefTextProps) {
  const brief = data.structuredData

  const formatList = (items: string[], prefix = '■ '): string => {
    return items.map((item) => `${prefix}${item}`).join('\n')
  }

  // Build header
  const flag = brief.countryCode ? countryCodeToFlag(brief.countryCode) : '🌍'
  const cityName = toTitleCase(brief.destination).toUpperCase()
  const travelTime =
    data.travelMonth ||
    (brief.startDate && brief.endDate ? `${brief.startDate} — ${brief.endDate}` : '')

  let formattedText = `# ${flag} ${cityName}\n`
  if (travelTime) {
    formattedText += `**${travelTime}**\n`
  }
  formattedText += '\n---\n'

  // Transportation section
  if (brief.transportation?.tips?.length) {
    formattedText += `\n## 🚇 TRANSPORTATION\n\n${formatList(brief.transportation.tips)}\n`
  }

  // Neighborhoods section
  if (brief.neighborhoods?.areas?.length) {
    formattedText += `\n## 🏘️ NEIGHBORHOODS\n\n`
    formattedText += brief.neighborhoods.areas
      .map((area) => `■ **${area.name}**: ${area.character}`)
      .join('\n')
    if (brief.neighborhoods.whereToStay?.length) {
      formattedText += '\n\n' + formatList(brief.neighborhoods.whereToStay)
    }
    formattedText += '\n'
  }

  // Food & Drink section
  if (brief.foodAndDrink?.restaurants?.length || brief.foodAndDrink?.tipping?.length) {
    formattedText += `\n## 🍽️ FOOD & DRINK\n\n`
    if (brief.foodAndDrink.restaurants?.length) {
      formattedText += formatList(brief.foodAndDrink.restaurants) + '\n'
    }
    if (brief.foodAndDrink.tipping?.length) {
      formattedText += '\n' + formatList(brief.foodAndDrink.tipping) + '\n'
    }
  }

  // Attractions section
  if (brief.attractions) {
    const allAttractions = [
      ...(brief.attractions.mustSee || []),
      ...(brief.attractions.offTheBeatenPath || []),
    ]
    if (allAttractions.length > 0) {
      formattedText += `\n## 📸 ATTRACTIONS\n\n${formatList(allAttractions)}\n`
    }
  }

  // Day Trips section
  if (brief.dayTrips?.nearbyDestinations?.length) {
    formattedText += `\n## 🗺️ DAY TRIPS\n\n${formatList(brief.dayTrips.nearbyDestinations)}\n`
  }

  // Staying Active section
  if (brief.activeAndSports?.outdoorActivities?.length) {
    formattedText += `\n## 🏃 STAYING ACTIVE\n\n${formatList(brief.activeAndSports.outdoorActivities)}\n`
  }

  // Quick Reference
  if (brief.practical) {
    formattedText += `\n## ⚡ QUICK REFERENCE\n\n`
    if (brief.practical.currency) {
      formattedText += `**Currency:** ${brief.practical.currency}\n\n`
    }
    if (brief.practical.language?.length) {
      formattedText += `**Language:** ${brief.practical.language.join(', ')}\n\n`
    }
    if (brief.practical.emergency?.length) {
      formattedText += `**Emergency:** ${brief.practical.emergency.join(', ')}\n\n`
    }
    if (brief.practical.safety?.length) {
      formattedText += `**Safety:**\n${formatList(brief.practical.safety)}\n\n`
    }
    if (brief.practical.commonScams?.length) {
      formattedText += `**Scams to Avoid:**\n${formatList(brief.practical.commonScams)}\n`
    }
  }

  formattedText += `\n---\n\n*Generated by TripBrief • Double-check current information before traveling*`

  return (
    <div className="bg-swiss-white border border-swiss-gray-200 rounded-swiss-lg shadow-swiss-md p-12">
      <div className="prose max-w-none">
        <div className="whitespace-pre-wrap font-mono text-sm leading-relaxed text-swiss-gray-700">
          {formattedText}
        </div>
      </div>
    </div>
  )
}
