import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service - TripBrief',
  description:
    "Read TripBrief's Terms of Service including usage guidelines, information disclaimers, and acceptable use policies for our AI travel planning service.",
  robots: {
    index: false,
    follow: true,
  },
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-swiss-white">
      <main className="container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto bg-swiss-white border border-swiss-gray-200 rounded-swiss-lg shadow-swiss-md p-12">
          <div className="text-center mb-12">
            <h1 className="text-4xl font-bold text-swiss-black mb-4">Terms of Service</h1>
            <p className="text-swiss-gray-600">Last updated: {new Date().toLocaleDateString()}</p>
          </div>

          <div className="prose max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-swiss-black mb-4">
                1. Acceptance of Terms
              </h2>
              <p className="text-swiss-gray-700 mb-4">
                By accessing and using TripBrief, you accept and agree to be bound by the terms and
                provision of this agreement. If you do not agree to abide by the above, please do
                not use this service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                2. Service Description
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                TripBrief is a travel information service that uses artificial intelligence to
                generate travel briefs for destinations. The service provides information about
                transportation, attractions, food, culture, and practical travel tips.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                3. Information Disclaimer
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                <strong>Important:</strong> All travel information provided by TripBrief is
                generated by artificial intelligence and should be considered for informational
                purposes only. We strongly recommend that you:
              </p>
              <ul className="list-disc pl-6 text-gray-700 dark:text-gray-300 mb-4">
                <li>Verify all information before making travel decisions</li>
                <li>Check current travel advisories and restrictions</li>
                <li>Confirm business hours, prices, and availability</li>
                <li>Consult official sources for critical information</li>
              </ul>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                TripBrief is not liable for any inaccuracies, outdated information, or consequences
                arising from the use of our service.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                4. Acceptable Use
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                You agree to use TripBrief responsibly and within the following guidelines:
              </p>
              <ul className="list-disc pl-6 text-gray-700 dark:text-gray-300 mb-4">
                <li>Respect rate limits (maximum 3 requests per minute, 10 per hour)</li>
                <li>Do not attempt to circumvent usage restrictions</li>
                <li>Do not use automated scripts or bots to access the service</li>
                <li>Do not use the service for any illegal or unauthorized purpose</li>
                <li>Do not attempt to overload or disrupt the service</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                5. Email Communications
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                If you choose to subscribe to our newsletter or provide your email address:
              </p>
              <ul className="list-disc pl-6 text-gray-700 dark:text-gray-300 mb-4">
                <li>We may send you travel-related content, updates, and promotional materials</li>
                <li>You can unsubscribe at any time using the link in our emails</li>
                <li>We will not sell or share your email with third parties for marketing</li>
                <li>We may use your email for service-related communications</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibent text-gray-900 dark:text-white mb-4">
                6. Privacy and Data Collection
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                Your privacy is important to us. Please review our Privacy Policy to understand how
                we collect, use, and protect your information. By using TripBrief, you consent to
                the data practices described in our Privacy Policy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                7. Limitation of Liability
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                TripBrief and its operators shall not be liable for any direct, indirect,
                incidental, special, or consequential damages resulting from the use or inability to
                use the service, including but not limited to:
              </p>
              <ul className="list-disc pl-6 text-gray-700 dark:text-gray-300 mb-4">
                <li>Travel disruptions or changes</li>
                <li>Inaccurate or outdated information</li>
                <li>Financial losses related to travel decisions</li>
                <li>Service interruptions or technical issues</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                8. Modifications
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                We reserve the right to modify these terms at any time. Changes will be effective
                immediately upon posting. Your continued use of the service constitutes acceptance
                of any modifications.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-semibold text-gray-900 dark:text-white mb-4">
                9. Contact Information
              </h2>
              <p className="text-gray-700 dark:text-gray-300 mb-4">
                If you have any questions about these Terms of Service, please contact us at:
                support@tripbrief.io
              </p>
            </section>
          </div>
        </div>
      </main>
    </div>
  )
}
